services:

  reverseproxy:
      image: nginx:alpine
      ports:
        - "3000:80"
      depends_on:
        - backend
        - frontend
      volumes:
        - ./nginx/reverseproxy.conf:/etc/nginx/conf.d/default.conf:ro
      restart: unless-stopped

  backend:
    image: docker.petarmc.com/petarmc/gitrss-backend:latest
    container_name: backend
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
#      GITHUB_TOKEN: ${GITHUB_TOKEN:-} #optional, if not provided, unauthenticated requests will be made to the github api which will result in lower rate limits
      DEEP_REFRESH_DAYS: 10
    restart: unless-stopped


  frontend:
    image: docker.petarmc.com/petarmc/gitrss-frontend:latest
    container_name: frontend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis-data:/data
    # adjust max memory depending on expected load
    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru

volumes:
  redis-data:
